# Generated by Django 5.2 on 2025-04-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_en',
            field=models.CharField(max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ru',
            field=models.CharField(max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='subcategories_name_en',
            field=models.CharField(max_length=46, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='subcategories_name_ru',
            field=models.CharField(max_length=46, null=True, unique=True),
        ),
    ]
