# Generated by Django 5.2 on 2025-04-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_category_category_name_en_category_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cteated_date',
            new_name='created_date',
        ),
    ]
